{
	"version": 1495040239,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/1mm_title-sheet0.png",
		"images/1mm_playgame-sheet0.png",
		"images/1mm_bg2.png",
		"images/1mm_about1-sheet0.png",
		"images/0about_bg-sheet0.png",
		"images/0about_majid-sheet0.png",
		"images/0about_umar-sheet0.png",
		"images/0about_ajib-sheet0.png",
		"images/0about_mm1-sheet0.png",
		"images/0about_mm2-sheet0.png",
		"images/9m2k-sheet0.png",
		"images/9seameo-sheet0.png",
		"images/1mm_bg1.png",
		"images/2narasi_bg1.png",
		"images/2narasi_house1-sheet0.png",
		"images/2narasi_house2-sheet0.png",
		"images/2narasi_house3-sheet0.png",
		"images/2narasi_trees-sheet0.png",
		"images/2narasi_bg2.png",
		"images/2narasi_street.png",
		"images/2narasi_text1-sheet0.png",
		"images/2narasi_text2-sheet0.png",
		"images/2narasi_next-sheet0.png",
		"images/2narasi_cloud-sheet0.png",
		"images/2narasi_sun-sheet0.png",
		"images/3training_bg2.png",
		"images/3training_trees3angle.png",
		"images/3training_treescircle.png",
		"images/3training_floor.png",
		"images/3training_treesfront.png",
		"images/3training_sun-sheet0.png",
		"images/3training_birdsl-sheet0.png",
		"images/3training_target-sheet0.png",
		"images/3training_player-sheet0.png",
		"images/3training_player-sheet1.png",
		"images/3training_player-sheet2.png",
		"images/3training_arrow-sheet0.png",
		"images/1mm_intro-sheet0.png",
		"images/1mm_intro-sheet1.png",
		"images/1mm_intro-sheet2.png",
		"images/0about_title-sheet0.png",
		"images/4cave_floor.png",
		"images/3training_gvarrow-sheet0.png",
		"images/3training_birdsr-sheet0.png",
		"images/4cave_bg2.png",
		"images/4cave_bg1.png",
		"images/4cave_pilar.png",
		"images/4cave_ceiling.png",
		"images/3training_targetreal-sheet0.png",
		"images/3training_rock-sheet0.png",
		"images/4cave_spike-sheet0.png",
		"images/4cave_gas1.png",
		"images/4cave_cp-sheet0.png",
		"images/3training_text-sheet0.png",
		"images/3training_1bg.png",
		"images/3training_insarrow-sheet0.png",
		"images/3training_insclick-sheet0.png",
		"images/3training_insarrowleft-sheet0.png",
		"images/3training_insarrowup-sheet0.png",
		"images/3training_insarrowdown-sheet0.png",
		"images/3training_insarrowright-sheet0.png",
		"images/3training_insclick1-sheet0.png",
		"images/3training_insclick2-sheet0.png",
		"images/3training_insclickbird-sheet0.png",
		"images/4cave_batr-sheet0.png",
		"images/4cave_batr-sheet1.png",
		"images/4cave_batl-sheet0.png",
		"images/4cave_batl-sheet1.png",
		"images/4cave_ghost-sheet0.png",
		"images/4cave_ghostarrow-sheet0.png",
		"images/4cave_stars2-sheet0.png",
		"images/4cave_stars1-sheet0.png",
		"images/4cave_text-sheet0.png",
		"images/4cave_ins-sheet0.png",
		"images/4cave_life-sheet0.png",
		"images/5war_floor3.png",
		"images/5war_floor1.png",
		"images/5war_floor4-sheet0.png",
		"images/5war_ghost-sheet0.png",
		"images/5war_floor2-sheet0.png",
		"images/5war_monster-sheet0.png",
		"images/5war_monster-sheet1.png",
		"images/5war_skeleton-sheet0.png",
		"images/5war_bg.png",
		"images/5war_skeletonarrow-sheet0.png",
		"images/5war_rock-sheet0.png",
		"images/5war_text-sheet0.png",
		"images/5war_ins-sheet0.png",
		"images/0about_umartext1-sheet0.png",
		"images/0about_majidtext1-sheet0.png",
		"images/0about_ajibtext1-sheet0.png",
		"images/0about_ajibgameartist-sheet0.png",
		"images/0about_majidgamedesginer-sheet0.png",
		"images/0about_umargameprogrammer-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground.png",
		"images/spritefont.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"media/coin.m4a",
		"media/coin.ogg",
		"media/fail.m4a",
		"media/fail.ogg",
		"media/jump.m4a",
		"media/jump.ogg",
		"media/button clicked sound.m4a",
		"media/button clicked sound.ogg",
		"media/dead or decreased hp.m4a",
		"media/dead or decreased hp.ogg",
		"media/final stage sound.m4a",
		"media/final stage sound.ogg",
		"media/shooting arrow sound.m4a",
		"media/shooting arrow sound.ogg",
		"media/bgm main scene.ogg",
		"media/cave.ogg",
		"media/final stage.ogg",
		"media/training stage.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}